server:
  port: 8000

spring:
  profiles:
    active: dev2

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.coderjiang.pojo.entities
mapper:
  mappers: com.coderjiang.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL
debug: true

