# \u5E94\u7528\u670D\u52A1 WEB \u8BBF\u95EE\u7AEF\u53E3
server:
  port: 8080

spring:
  profiles:
    active: dev

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.coderjiang.pojo.entities
mapper:
  mappers: com.coderjiang.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL
debug: true

